version: '3.8'

services:
  sentinelx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentinelx
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8000:8000"  # API port
    environment:
      - PYTHONPATH=/app
      - TZ=UTC
    # Network mode host is needed for packet capture
    # Uncomment the line below when you need to capture packets
    # network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - apparmor:unconfined
    # Command to run the API server
    command: python src/api/api_server.py

  # Uncomment the section below if you want to add a database for alert storage
  # mongodb:
  #   image: mongo:5.0
  #   container_name: sentinelx-mongodb
  #   restart: unless-stopped
  #   volumes:
  #     - mongodb_data:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=sentinelx
  #     - MONGO_INITDB_ROOT_PASSWORD=sentinelx_password
  #   ports:
  #     - "27017:27017"

# Uncomment if using MongoDB
# volumes:
#   mongodb_data: