# SentinelX Configuration File

# General Settings
general:
  project_name: SentinelX
  version: 0.1.0
  debug_mode: true

# Paths Configuration
paths:
  data_dir: ../data
  models_dir: ../models
  logs_dir: ../logs

# Logging Configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: sentinelx.log
  max_size_mb: 10
  backup_count: 5

# Data Processing
data_processing:
  dataset: NSL-KDD  # Options: NSL-KDD, CICIDS2017, UNSW-NB15
  train_test_split: 0.8
  feature_scaling: true
  one_hot_encoding: true

# Model Configuration
model:
  type: RandomForest  # Options: RandomForest, XGBoost, LSTM, Transformer
  hyperparameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  save_model: true
  evaluation_metrics:
    - accuracy
    - precision
    - recall
    - f1_score

# Threat Intelligence
threat_intelligence:
  sources:
    - name: AlienVault OTX
      enabled: true
      api_key: YOUR_API_KEY_HERE
      cache_ttl_minutes: 60
    - name: AbuseIPDB
      enabled: true
      api_key: YOUR_API_KEY_HERE
      cache_ttl_minutes: 60
    - name: VirusTotal
      enabled: false
      api_key: YOUR_API_KEY_HERE
      cache_ttl_minutes: 120

# Network Monitoring
network_monitoring:
  interface: eth0  # Network interface to monitor
  packet_capture:
    enabled: true
    max_packets: 1000
    timeout_seconds: 60
  pcap_storage:
    enabled: true
    max_size_mb: 100
    retention_days: 7

# API Configuration
api:
  host: 0.0.0.0
  port: 8000
  debug: true
  rate_limit:
    enabled: true
    requests_per_minute: 60
  authentication:
    enabled: false
    method: api_key  # Options: api_key, jwt, oauth2

# Alert Configuration
alerts:
  threshold:
    low: 0.5
    medium: 0.7
    high: 0.9
  notification:
    email:
      enabled: false
      smtp_server: smtp.example.com
      smtp_port: 587
      sender: alerts@sentinelx.example.com
      recipients:
        - admin@example.com
    webhook:
      enabled: false
      url: https://example.com/webhook
    discord:
      enabled: false
      webhook_url: YOUR_DISCORD_WEBHOOK_URL

# Auto Response
auto_response:
  enabled: false
  actions:
    block_ip:
      enabled: false
      duration_minutes: 60
    log_event:
      enabled: true
    notify_admin:
      enabled: true